// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RezervasyonWebApp.Data.Concrete.EfCore;

namespace RezervasyonWebApp.Data.Migrations
{
    [DbContext(typeof(RezervasyonWebAppContext))]
    [Migration("20220521231018_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("RezervasyonWebApp.Entity.Bilet", b =>
                {
                    b.Property<int>("BiletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<double>("Fiyat")
                        .HasColumnType("REAL");

                    b.Property<int>("GuzergahId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KoltukNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nereden")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nereye")
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .HasColumnType("TEXT");

                    b.HasKey("BiletId");

                    b.HasIndex("GuzergahId");

                    b.ToTable("Bilets");
                });

            modelBuilder.Entity("RezervasyonWebApp.Entity.Guzergah", b =>
                {
                    b.Property<int>("GuzergahId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslangic")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bitis")
                        .HasColumnType("TEXT");

                    b.Property<double>("Fiyat")
                        .HasColumnType("REAL");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Saat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("guzergah1")
                        .HasColumnType("TEXT");

                    b.Property<string>("guzergah2")
                        .HasColumnType("TEXT");

                    b.Property<string>("guzergah3")
                        .HasColumnType("TEXT");

                    b.HasKey("GuzergahId");

                    b.ToTable("Guzergahs");
                });

            modelBuilder.Entity("RezervasyonWebApp.Entity.Sehir", b =>
                {
                    b.Property<int>("SehirId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SehirAd")
                        .HasColumnType("TEXT");

                    b.HasKey("SehirId");

                    b.ToTable("Sehirs");
                });

            modelBuilder.Entity("RezervasyonWebApp.Entity.Bilet", b =>
                {
                    b.HasOne("RezervasyonWebApp.Entity.Guzergah", "guzergah")
                        .WithMany("Bilets")
                        .HasForeignKey("GuzergahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("guzergah");
                });

            modelBuilder.Entity("RezervasyonWebApp.Entity.Guzergah", b =>
                {
                    b.Navigation("Bilets");
                });
#pragma warning restore 612, 618
        }
    }
}
